version: '3'

services:
  postgres:
    image: postgres
    domainname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=wallet_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_already", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  liquibase:
    image: liquibase/liquibase
    command: --url=jdbc:postgresql://postgres:5432/postgres?user=postgres&password=postgres --changeLogFile=changelog.xml update
    volumes:
      - ./src/main/resources/db/changelog/changelog.xml:/liquibase/changelog.xml
      - ./src/main/resources/db/changelog/001-create-table.xml:/liquibase/001-create-table.xml
      - ./src/main/resources/db/changelog/002-insert-data.xml:/liquibase/002-insert-data.xml
    depends_on:
      - postgres



